In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../Notebook/data_clean/clusters_subdistricts.csv')
df

,lor,subdistrict,area,district,density,popul,crime_total,robbery,theft_bike,theft_other,...,nb_a,area_f,nb_f,area_c,nb_c,area_p,nb_p,area_g,nb_g,cluster
0,11001,Tiergarten Süd,517,Mitte,29.50,15249,25169,230,1541,8197,...,0,0.00,0,0.00,0,226.75,38,0.00,0,2
1,11002,Regierungsviertel,270,Mitte,48.41,13071,45567,252,1882,13664,...,0,0.00,0,0.00,0,5.80,12,0.00,0,2
2,11003,Alexanderplatz,623,Mitte,95.66,59594,26454,258,1248,9451,...,0,0.00,0,5.87,4,43.97,78,0.00,0,2
3,11004,Brunnenstraße Süd,176,Mitte,179.07,31516,10788,133,1149,3544,...,0,0.00,0,12.64,3,10.33,9,0.00,0,4
4,12005,Moabit West,431,Mitte,105.97,45674,13207,105,849,3339,...,0,0.00,0,0.00,0,11.04,22,0.00,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,125008,West 3 - Borsigwalde/Freie Scholle,408,Reinickendorf,40.13,16372,6621,24,397,1936,...,6,8.10,1,16.55,4,6.75,15,21.05,6,1
139,125009,Nord 2 - Waidmannslust/Wittenau/Lübars,1180,Reinickendorf,27.19,32080,13223,84,346,3373,...,11,1.97,1,6.12,2,187.73,40,52.91,11,0
140,126010,Rollbergesiedlung,164,Reinickendorf,55.81,9153,9155,44,186,3868,...,4,0.00,0,0.00,0,7.60,4,13.48,4,5
141,126011,MV Nord,205,Reinickendorf,130.38,26728,7909,79,247,2604,...,2,0.00,0,0.00,0,3.41,5,6.78,2,5
142,126012,MV Süd,110,Reinickendorf,124.72,13719,5715,58,160,1254,...,0,0.00,0,0.00,0,1.46,2,0.00,0,5

In [3]:
def format(zahl):
    # Correcting lor: all unique lor should have 6 characters. 
    newZahl = "0"
    if len(str(zahl)) == 5:
        newZahl = newZahl + str(zahl)
    else: newZahl = str(zahl)

    return newZahl

In [4]:
df['lor'] = df['lor'].apply(format)

In [6]:
pd.set_option('display.max_columns', None)  # to see all columns
df

,lor,subdistrict,area,district,density,popul,crime_total,robbery,theft_bike,theft_other,bulglary,graffiti,drug_offences,hard_crime,other_crime,area_objects,nb_objects,area_a,nb_a,area_f,nb_f,area_c,nb_c,area_p,nb_p,area_g,nb_g,cluster
0,011001,Tiergarten Süd,517,Mitte,29.50,15249,25169,230,1541,8197,157,289,1312,2912,10532,229.64,54,0.00,0,0.00,0,0.00,0,226.75,38,0.00,0,2
1,011002,Regierungsviertel,270,Mitte,48.41,13071,45567,252,1882,13664,122,826,1316,4307,23196,6.37,15,0.00,0,0.00,0,0.00,0,5.80,12,0.00,0,2
2,011003,Alexanderplatz,623,Mitte,95.66,59594,26454,258,1248,9451,129,530,1438,3101,10298,56.18,128,0.00,0,0.00,0,5.87,4,43.97,78,0.00,0,2
3,011004,Brunnenstraße Süd,176,Mitte,179.07,31516,10788,133,1149,3544,102,324,400,1088,4049,26.79,26,0.00,0,0.00,0,12.64,3,10.33,9,0.00,0,4
4,012005,Moabit West,431,Mitte,105.97,45674,13207,105,849,3339,151,217,1141,1738,5666,15.22,51,0.00,0,0.00,0,0.00,0,11.04,22,0.00,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,125008,West 3 - Borsigwalde/Freie Scholle,408,Reinickendorf,40.13,16372,6621,24,397,1936,128,43,147,1069,2877,54.45,35,21.05,6,8.10,1,16.55,4,6.75,15,21.05,6,1
139,125009,Nord 2 - Waidmannslust/Wittenau/Lübars,1180,Reinickendorf,27.19,32080,13223,84,346,3373,209,249,315,1393,7254,251.19,65,52.91,11,1.97,1,6.12,2,187.73,40,52.91,11,0
140,126010,Rollbergesiedlung,164,Reinickendorf,55.81,9153,9155,44,186,3868,109,33,98,1322,3496,21.97,11,13.48,4,0.00,0,0.00,0,7.60,4,13.48,4,5
141,126011,MV Nord,205,Reinickendorf,130.38,26728,7909,79,247,2604,49,34,168,1598,3132,11.72,13,6.78,2,0.00,0,0.00,0,3.41,5,6.78,2,5
142,126012,MV Süd,110,Reinickendorf,124.72,13719,5715,58,160,1254,80,7,131,1254,2770,1.70,3,0.00,0,0.00,0,0.00,0,1.46,2,0.00,0,5

In [11]:
df["ratio_green"] = ((df["area_objects"]/df["area"])*100).round(2)

In [12]:
df

,lor,subdistrict,area,district,density,popul,crime_total,robbery,theft_bike,theft_other,bulglary,graffiti,drug_offences,hard_crime,other_crime,area_objects,nb_objects,area_a,nb_a,area_f,nb_f,area_c,nb_c,area_p,nb_p,area_g,nb_g,cluster,ratio_green
0,011001,Tiergarten Süd,517,Mitte,29.50,15249,25169,230,1541,8197,157,289,1312,2912,10532,229.64,54,0.00,0,0.00,0,0.00,0,226.75,38,0.00,0,2,44.42
1,011002,Regierungsviertel,270,Mitte,48.41,13071,45567,252,1882,13664,122,826,1316,4307,23196,6.37,15,0.00,0,0.00,0,0.00,0,5.80,12,0.00,0,2,2.36
2,011003,Alexanderplatz,623,Mitte,95.66,59594,26454,258,1248,9451,129,530,1438,3101,10298,56.18,128,0.00,0,0.00,0,5.87,4,43.97,78,0.00,0,2,9.02
3,011004,Brunnenstraße Süd,176,Mitte,179.07,31516,10788,133,1149,3544,102,324,400,1088,4049,26.79,26,0.00,0,0.00,0,12.64,3,10.33,9,0.00,0,4,15.22
4,012005,Moabit West,431,Mitte,105.97,45674,13207,105,849,3339,151,217,1141,1738,5666,15.22,51,0.00,0,0.00,0,0.00,0,11.04,22,0.00,0,4,3.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,125008,West 3 - Borsigwalde/Freie Scholle,408,Reinickendorf,40.13,16372,6621,24,397,1936,128,43,147,1069,2877,54.45,35,21.05,6,8.10,1,16.55,4,6.75,15,21.05,6,1,13.35
139,125009,Nord 2 - Waidmannslust/Wittenau/Lübars,1180,Reinickendorf,27.19,32080,13223,84,346,3373,209,249,315,1393,7254,251.19,65,52.91,11,1.97,1,6.12,2,187.73,40,52.91,11,0,21.29
140,126010,Rollbergesiedlung,164,Reinickendorf,55.81,9153,9155,44,186,3868,109,33,98,1322,3496,21.97,11,13.48,4,0.00,0,0.00,0,7.60,4,13.48,4,5,13.40
141,126011,MV Nord,205,Reinickendorf,130.38,26728,7909,79,247,2604,49,34,168,1598,3132,11.72,13,6.78,2,0.00,0,0.00,0,3.41,5,6.78,2,5,5.72
142,126012,MV Süd,110,Reinickendorf,124.72,13719,5715,58,160,1254,80,7,131,1254,2770,1.70,3,0.00,0,0.00,0,0.00,0,1.46,2,0.00,0,5,1.55

In [13]:
df.to_csv('clusters_subdistricts_edit.csv', index=False)